// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvQ5gElK2G3MhJPoW5iZCwRqUPGu4r4qg',
    appId: '1:5216814524:web:551a89b6ad87784bbe57b9',
    messagingSenderId: '5216814524',
    projectId: 'site-cycle-6340d',
    authDomain: 'site-cycle-6340d.firebaseapp.com',
    storageBucket: 'site-cycle-6340d.appspot.com',
    measurementId: 'G-1PQ6DN0R5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDthhwmAS69eO04f_i1foM08gTHFarV-VU',
    appId: '1:5216814524:android:86ed1af5cfcbcd09be57b9',
    messagingSenderId: '5216814524',
    projectId: 'site-cycle-6340d',
    storageBucket: 'site-cycle-6340d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJf0ChLz2MM7APO5Pr5fgYPu5sOzUBaSw',
    appId: '1:5216814524:ios:a748478245141ccbbe57b9',
    messagingSenderId: '5216814524',
    projectId: 'site-cycle-6340d',
    storageBucket: 'site-cycle-6340d.appspot.com',
    iosBundleId: 'com.example.sitecycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJf0ChLz2MM7APO5Pr5fgYPu5sOzUBaSw',
    appId: '1:5216814524:ios:a748478245141ccbbe57b9',
    messagingSenderId: '5216814524',
    projectId: 'site-cycle-6340d',
    storageBucket: 'site-cycle-6340d.appspot.com',
    iosBundleId: 'com.example.sitecycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvQ5gElK2G3MhJPoW5iZCwRqUPGu4r4qg',
    appId: '1:5216814524:web:787caf75eb662f72be57b9',
    messagingSenderId: '5216814524',
    projectId: 'site-cycle-6340d',
    authDomain: 'site-cycle-6340d.firebaseapp.com',
    storageBucket: 'site-cycle-6340d.appspot.com',
    measurementId: 'G-35D0ZZ66Q6',
  );
}
